image: gitpod/workspace-node

tasks:
    - command: |
          npm i -g bun
          bun install
          cp .env.example .env
          ./scripts/gitpod.sh
          bun dev

vscode:
    extensions:
        - "oven.bun-vscode"
        - "bradlc.vscode-tailwindcss"
        - "rvest.vs-code-prettier-eslint"
