image: gitpod/workspace-node

tasks:
    - init: |
          npm i -g bun
          bun install
          cp .env.example .env
          bun run db:push
          bun run prisma/seed.ts
      command: bun dev
