/* eslint-disable @typescript-eslint/no-unsafe-call */
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { createClientComponentClient } from "@supabase/auth-helpers-nextjs";
import Head from "next/head";

export default function Home() {
    const supabase = createClientComponentClient();

    const handleSignIn = () => {
        supabase.auth
            .signInWithOAuth({
                provider: "google",
            })
            .catch((error) => {
                console.log(error);
            });
    };

    return (
        <>
            <Head>
                <title>MMP</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
                    <Card>
                        <CardHeader className="space-y-1">
                            <CardTitle className="text-2xl">Pokračovat do seminářů</CardTitle>
                            <CardDescription>Přihlašování do aplikace probíhá přes školní Google účet.</CardDescription>
                        </CardHeader>
                        <CardContent className="grid gap-4"></CardContent>
                        <CardFooter>
                            <Button className="w-full" onClick={handleSignIn}>
                                Přihlásit se
                            </Button>
                        </CardFooter>
                    </Card>
                </div>
            </main>
        </>
    );
}
