version: "3.8"
services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/base:ubuntu
        volumes:
            - ../..:/workspaces:cached
        network_mode: service:db
        command: sleep infinity

    db:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: development
            POSTGRES_USER: postgres
            POSTGRES_DB: interclip

volumes:
    postgres-data:
